version: 0.0.1

firebase:
  apiKey: "AIzaSyDwUfnowFD3uaZygif_d26R5f8rnqAzjDE"
  authDomain: "alienlabs-dev.firebaseapp.com"
  databaseURL: "https://alienlabs-dev.firebaseio.com"
  projectId: "alienlabs-dev"
  storageBucket: "alienlabs-dev.appspot.com"
  messagingSenderId: "933786919888"

firebase_admin:
  serverKey: "AAAA2WoJo9A:APA91bHz3soGENkkRJNI5yZ4C8ywA157b3J7uIxpyiTRAw6_doNxAbivXIMYP-fOoyPR1KxRmvaXF9qpaEXoKI9NIpYvCS-5vmMK-HSQZj7CyG_2lqUalHK0htOG5MmRdBRttGUS0gVu"

firebase_credentials:
  type: "service_account"
  project_id: "alienlabs-dev"
  private_key_id: "e07a9566cbfdb6b539923dcd2bcc3f7a13830194"
  private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDJjmTnpJiY7ChL\ndwc/LqujRWyCZ8T9C4k+Fg1uwIk3BlNdTg9wQb6gbayYoGJeY0xD9G7W4uWdpOqe\nCx1lFbpFoy9glssZObWuao5crYk+erv23r8gZ1Ko+1af2/z4O4V8Xiwi8gfPCDqc\nXdgjNjWLqsrFauSLr9XCQ2Tcqq3IdoNx9YA2xhSP8yuoBtjEiP9y5yOn3+PbnggY\n0YUjKVDbpgfXRe5keZvDiepzfcM0PxdEMHKOkCy0/9XUKqXuQPG5Tk5m4tlc5tN4\n5s22mxolrH3e4L2qZfISiByfioOLM0fqS3iR5fgHZqtloxEEOHUR2vFlQT2/Bl3g\nZBS4YrsDAgMBAAECggEBAJ+loBsy7oPCGrCbmSvchasPZEFufEOKjayVvxIIgycI\nZaO0Htpl2N4twNYrw37L3C6/P8QJeKKDbCq+1wuoSCC8ftxc1IYohdWfJSAXfGv2\nv0dta6n47SpX2mdI0ni0fKjj1sXfO3wrInGUi4xodcUpBO+WGWzjW8dBpnR65Kew\nfyCwPDY45lUK8YGIqm/ZT1WXvt9h7J8/yWQHVqVXHHCu54rRf6oU6lVWsjdyk13Q\n0nt6cEgikjh2qQJXSd/D3ueJXRgYsZbRut2feQTZq5YxQ1k6/gSQxF5eFbnZKq3v\na9FGHgXIJEtqm8bTFwkS66xybENf+3WX58rZBlSTQQECgYEA8fDzuy9xmek2+qDE\n0/R/c33GqpNqr3J5R0qtCtv7DB0plOYbwRtaiuWfTbkcoua8JCnAWBDAXtu2xgiS\neKVQ+xkUwLpV/Zh3Fx1GmrFgwAvuFt9PVzswrQg7HhcdR7NiKJ0p8xBJP/LvSTK4\nZQxRDerZFH/brP44DjKdcaxiOsMCgYEA1USvwymHuca3G/fPrLEqqV1+gbRlXUcz\nwwZ/UxGBmp/LhXdwBBlPup8fQSMun1lbOBXOuPsUkZleCxr2XBm2p51QWB6Pby98\nQ3y+rGpXojsi7jsFlTAyq8oq9zb4xqwfTyyIhtGQC2CG7phG2qj6hifV1v0vhU3V\nW0tCDLQm+sECgYEA05PDkY6L6ezpB4RQnIrUaksz0TfZtFSHerDzYuu9P3rBQlV5\nMAabx5vHFFEtmcfuADIC4wDDOjEqRUR50se/adclLuXFDWCnxK71b5Ju6YOFUrs2\nxzIb/zWTfVz5XhqhXKMUbFtxs1rfp0OTvcpnl6Qo8qRdl4s5ujDJPv9hZ8ECgYEA\niVDpblqOJmK5QYvErqeAFX66Vp8laPLQdDD5yC2Malea/juR50G44StVP2Z8vWMW\nZb081kPr0XeTYskgeNqhjbivo51Bs1A6zWVDi9YIyM8UxZlBFfbrmUrZcUV21sy6\neArveQbznS+wkW2AqYeFjt2VRRDOCSG9T0PcqjtQocECgYBtD6rfYGcNA98MHjlf\n5sPA06wcBB8fN656T0Itrn4Rw5ddrKEfvRMoWj0G5lza5WvrGmDZKnOWHZmxH/bk\n4e7xf6bJ8spEfQCCwX4O12wejJr0uWSjErjr8UiK8RlsSxR5ta+Qaa6LpdUXGCVd\nGRtUFdBpxqUNUu40O4uJkmgpXg==\n-----END PRIVATE KEY-----\n"
  client_email: "firebase-adminsdk-dmpna@alienlabs-dev.iam.gserviceaccount.com"
  client_id: "102153609950940838064"
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://accounts.google.com/o/oauth2/token"
  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-dmpna%40alienlabs-dev.iam.gserviceaccount.com"
